version: "3.8"

services:
  db:
    build: ./db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: battlesheep
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    environment:
      MYSQL_DATABASE: battlesheep
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "4200:4200"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    command: "node index.js"
